### ISSUE TITLE
设备列表点击“停用”，一直显示“释放中”

### ISSUE THREAD

**Issue by pepsicoffee** [openatx/atxserver2#14]
说明：
server：centos（docker 部署）
android-provider：win7（手工部署）
重现步骤：
设备连接上后，点击“停用”，一直显示“释放中”
备注：
- 服务器日志截图：
[I 190515 09:30:22 web:2246] 200 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 12.02ms
[I 190515 09:30:23 web:2246] 200 DELETE /api/v1/user/devices/6a5cde83 (192.168.255.254) 19.27ms
[I 190515 09:30:28 web:2246] 200 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 12.02ms
[I 190515 09:30:35 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 11.51ms
[I 190515 09:30:41 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 12.04ms
[E 190515 09:30:43 ioloop:763] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f89c99237f0>>, <Task finished coro=<D.release.<locals>.cold_device() done, defined at /app/web/views/device.py:466> exception=HTTP 599: Timeout while connecting>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
        future.result()
      File "/app/web/views/device.py", line 476, in cold_device
        await http_client.fetch(request)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting
[I 190515 09:30:47 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 11.35ms
[I 190515 09:30:52 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 12.21ms
[I 190515 09:30:58 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 11.21ms
7a1461f20630[I 190515 09:31:04 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 11.20ms
7a1461f20630[I 190515 09:31:11 web:2246] 304 GET /api/v1/user/devices/6a5cde83 (192.168.255.254) 11.42ms

- 现象截图：

![图片](https://user-images.githubusercontent.com/26764865/57764354-d7436100-7735-11e9-9466-ddfce611f1d1.png)

**Comment by codeskyblue** [comment]
先暴力处理了下，如果server通知provider重置设备失败，直接数据库中标记设备已释放
