### ISSUE TITLE
 设备屏幕同步中断，provider中提示apk安装失败

### ISSUE THREAD

**Issue by HBoPRC** [openatx/atxserver2#26]
连了 6 台设备，其中有两天出现了中断的问题；重启也不会安装apk，手机安全相关设置都关闭了
provider：
```
[D 190717 10:21:33 device:127] [7DAMTS79FIMVUKJR] install vendor/app-uiautomator.apk
Traceback (most recent call last):
  File "/home/youkia/git/atxserver2-android-provider/device.py", line 128, in _install_apk
    self._device.install(path)
  File "/usr/local/python3/lib/python3.7/site-packages/adbutils/mixin.py", line 126, in install
    self.install_remote(dst, clean=True)
  File "/usr/local/python3/lib/python3.7/site-packages/adbutils/mixin.py", line 144, in install_remote
    raise AdbInstallError(output)
adbutils.errors.AdbInstallError: 	pkg: /data/local/tmp/tmp-1563330093231.apk
Failure [INSTALL_FAILED_OLDER_SDK]
[W 190717 10:21:34 device:131] [7DAMTS79FIMVUKJR] Install apk vendor/app-uiautomator.apk error 	pkg: /data/local/tmp/tmp-1563330093231.apk
    Failure [INSTALL_FAILED_OLDER_SDK]
None :  
```
环境：
CentOS 7.4
Python 3.7.3
设备：
魅族 魅蓝 S6
atxserver2 和 provider 都是python3 手动启动的

**Comment by xdkaka** [comment]
CentOS  +1
