### ISSUE TITLE
安卓设备初始化失败

### ISSUE THREAD

**Issue by zutuanwang** [openatx/atxserver2#29]
[E 190806 02:59:38 main:258] Unknown error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "main.py", line 241, in device_watch
    await device.init()
  File "/app/device.py", line 59, in init
    self._init_binaries()
  File "/app/device.py", line 102, in _init_binaries
    zipfile_path="vendor/atx-agent-latest.zip")
  File "/app/device.py", line 112, in _push_stf
    self._device.sync.push(f, dest, mode)
  File "/usr/local/lib/python3.7/site-packages/adbutils/__init__.py", line 519, in push
    c.conn.send(b"DATA" + struct.pack("<I", len(chunk)))
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by GLTSC** [comment]
这个问题解决了嘛？
